# Pulling out all of the pokemon names from the thing.
from __future__ import annotations

import pickle

if __name__ == "__main__":
    list_of_poke_dicts = [
        {
            "name": "Bulbasaur",
            "hp": 45,
            "atk": 49,
            "def": 49,
            "spa": 65,
            "spd": 65,
            "spe": 45,
            "weight": 6.9,
            "height": 0.7,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 1,
                "evos": ["Ivysaur"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Caterpie",
            "hp": 45,
            "atk": 30,
            "def": 35,
            "spa": 20,
            "spd": 20,
            "spe": 45,
            "weight": 2.9,
            "height": 0.3,
            "types": ["Bug"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 10,
                "evos": ["Metapod"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Voltorb",
            "hp": 40,
            "atk": 30,
            "def": 50,
            "spa": 55,
            "spd": 55,
            "spe": 100,
            "weight": 10.4,
            "height": 0.5,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 100,
                "evos": ["Electrode"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Electrode",
            "hp": 60,
            "atk": 50,
            "def": 70,
            "spa": 80,
            "spd": 80,
            "spe": 140,
            "weight": 66.6,
            "height": 1.2,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 101,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Exeggcute",
            "hp": 60,
            "atk": 40,
            "def": 80,
            "spa": 60,
            "spd": 60,
            "spe": 40,
            "weight": 2.5,
            "height": 0.4,
            "types": ["Grass", "Psychic"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 102,
                "evos": ["Exeggutor"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Exeggutor",
            "hp": 95,
            "atk": 95,
            "def": 85,
            "spa": 125,
            "spd": 125,
            "spe": 55,
            "weight": 120,
            "height": 2,
            "types": ["Grass", "Psychic"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 103,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Cubone",
            "hp": 50,
            "atk": 50,
            "def": 95,
            "spa": 40,
            "spd": 40,
            "spe": 35,
            "weight": 6.5,
            "height": 0.4,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 104,
                "evos": ["Marowak"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Marowak",
            "hp": 60,
            "atk": 80,
            "def": 110,
            "spa": 50,
            "spd": 50,
            "spe": 45,
            "weight": 45,
            "height": 1,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 105,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Hitmonlee",
            "hp": 50,
            "atk": 120,
            "def": 53,
            "spa": 35,
            "spd": 35,
            "spe": 87,
            "weight": 49.8,
            "height": 1.5,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 106,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Hitmonchan",
            "hp": 50,
            "atk": 105,
            "def": 79,
            "spa": 35,
            "spd": 35,
            "spe": 76,
            "weight": 50.2,
            "height": 1.4,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 107,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Lickitung",
            "hp": 90,
            "atk": 55,
            "def": 75,
            "spa": 60,
            "spd": 60,
            "spe": 30,
            "weight": 65.5,
            "height": 1.2,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 108,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Koffing",
            "hp": 40,
            "atk": 65,
            "def": 95,
            "spa": 60,
            "spd": 60,
            "spe": 35,
            "weight": 1,
            "height": 0.6,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 109,
                "evos": ["Weezing"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Metapod",
            "hp": 50,
            "atk": 20,
            "def": 55,
            "spa": 25,
            "spd": 25,
            "spe": 30,
            "weight": 9.9,
            "height": 0.7,
            "types": ["Bug"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 11,
                "evos": ["Butterfree"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Weezing",
            "hp": 65,
            "atk": 90,
            "def": 120,
            "spa": 85,
            "spd": 85,
            "spe": 60,
            "weight": 9.5,
            "height": 1.2,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 110,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Rhyhorn",
            "hp": 80,
            "atk": 85,
            "def": 95,
            "spa": 30,
            "spd": 30,
            "spe": 25,
            "weight": 115,
            "height": 1,
            "types": ["Ground", "Rock"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 111,
                "evos": ["Rhydon"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Rhydon",
            "hp": 105,
            "atk": 130,
            "def": 120,
            "spa": 45,
            "spd": 45,
            "spe": 40,
            "weight": 120,
            "height": 1.9,
            "types": ["Ground", "Rock"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 112,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Chansey",
            "hp": 250,
            "atk": 5,
            "def": 5,
            "spa": 105,
            "spd": 105,
            "spe": 50,
            "weight": 34.6,
            "height": 1.1,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 113,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Tangela",
            "hp": 65,
            "atk": 55,
            "def": 115,
            "spa": 100,
            "spd": 100,
            "spe": 60,
            "weight": 35,
            "height": 1,
            "types": ["Grass"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 114,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kangaskhan",
            "hp": 105,
            "atk": 95,
            "def": 80,
            "spa": 40,
            "spd": 40,
            "spe": 90,
            "weight": 80,
            "height": 2.2,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 115,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Horsea",
            "hp": 30,
            "atk": 40,
            "def": 70,
            "spa": 70,
            "spd": 70,
            "spe": 60,
            "weight": 8,
            "height": 0.4,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 116,
                "evos": ["Seadra"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Seadra",
            "hp": 55,
            "atk": 65,
            "def": 95,
            "spa": 95,
            "spd": 95,
            "spe": 85,
            "weight": 25,
            "height": 1.2,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 117,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Goldeen",
            "hp": 45,
            "atk": 67,
            "def": 60,
            "spa": 50,
            "spd": 50,
            "spe": 63,
            "weight": 15,
            "height": 0.6,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 118,
                "evos": ["Seaking"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Seaking",
            "hp": 80,
            "atk": 92,
            "def": 65,
            "spa": 80,
            "spd": 80,
            "spe": 68,
            "weight": 39,
            "height": 1.3,
            "types": ["Water"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 119,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Butterfree",
            "hp": 60,
            "atk": 45,
            "def": 50,
            "spa": 80,
            "spd": 80,
            "spe": 70,
            "weight": 32,
            "height": 1.1,
            "types": ["Bug", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 12,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Staryu",
            "hp": 30,
            "atk": 45,
            "def": 55,
            "spa": 70,
            "spd": 70,
            "spe": 85,
            "weight": 34.5,
            "height": 0.8,
            "types": ["Water"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 120,
                "evos": ["Starmie"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Starmie",
            "hp": 60,
            "atk": 75,
            "def": 85,
            "spa": 100,
            "spd": 100,
            "spe": 115,
            "weight": 80,
            "height": 1.1,
            "types": ["Water", "Psychic"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 121,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Mr. Mime",
            "hp": 40,
            "atk": 45,
            "def": 65,
            "spa": 100,
            "spd": 100,
            "spe": 90,
            "weight": 54.5,
            "height": 1.3,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 122,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Scyther",
            "hp": 70,
            "atk": 110,
            "def": 80,
            "spa": 55,
            "spd": 55,
            "spe": 105,
            "weight": 56,
            "height": 1.5,
            "types": ["Bug", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 123,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Jynx",
            "hp": 65,
            "atk": 50,
            "def": 35,
            "spa": 95,
            "spd": 95,
            "spe": 95,
            "weight": 40.6,
            "height": 1.4,
            "types": ["Ice", "Psychic"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 124,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Electabuzz",
            "hp": 65,
            "atk": 83,
            "def": 57,
            "spa": 85,
            "spd": 85,
            "spe": 105,
            "weight": 30,
            "height": 1.1,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 125,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Magmar",
            "hp": 65,
            "atk": 95,
            "def": 57,
            "spa": 85,
            "spd": 85,
            "spe": 93,
            "weight": 44.5,
            "height": 1.3,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 126,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Pinsir",
            "hp": 65,
            "atk": 125,
            "def": 100,
            "spa": 55,
            "spd": 55,
            "spe": 85,
            "weight": 55,
            "height": 1.5,
            "types": ["Bug"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 127,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Tauros",
            "hp": 75,
            "atk": 100,
            "def": 95,
            "spa": 70,
            "spd": 70,
            "spe": 110,
            "weight": 88.4,
            "height": 1.4,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 128,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Magikarp",
            "hp": 20,
            "atk": 10,
            "def": 55,
            "spa": 20,
            "spd": 20,
            "spe": 80,
            "weight": 10,
            "height": 0.9,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 129,
                "evos": ["Gyarados"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Weedle",
            "hp": 40,
            "atk": 35,
            "def": 30,
            "spa": 20,
            "spd": 20,
            "spe": 50,
            "weight": 3.2,
            "height": 0.3,
            "types": ["Bug", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 13,
                "evos": ["Kakuna"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Gyarados",
            "hp": 95,
            "atk": 125,
            "def": 79,
            "spa": 100,
            "spd": 100,
            "spe": 81,
            "weight": 235,
            "height": 6.5,
            "types": ["Water", "Flying"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 130,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Lapras",
            "hp": 130,
            "atk": 85,
            "def": 80,
            "spa": 95,
            "spd": 95,
            "spe": 60,
            "weight": 220,
            "height": 2.5,
            "types": ["Water", "Ice"],
            "abilities": [],
            "formats": ["UUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 131,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Ditto",
            "hp": 48,
            "atk": 48,
            "def": 48,
            "spa": 48,
            "spd": 48,
            "spe": 48,
            "weight": 4,
            "height": 0.3,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 132,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Eevee",
            "hp": 55,
            "atk": 55,
            "def": 50,
            "spa": 65,
            "spd": 65,
            "spe": 55,
            "weight": 6.5,
            "height": 0.3,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 133,
                "evos": ["Flareon", "Jolteon", "Vaporeon"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Vaporeon",
            "hp": 130,
            "atk": 65,
            "def": 60,
            "spa": 110,
            "spd": 110,
            "spe": 65,
            "weight": 29,
            "height": 1,
            "types": ["Water"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 134,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Jolteon",
            "hp": 65,
            "atk": 65,
            "def": 60,
            "spa": 110,
            "spd": 110,
            "spe": 130,
            "weight": 24.5,
            "height": 0.8,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 135,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Flareon",
            "hp": 65,
            "atk": 130,
            "def": 60,
            "spa": 110,
            "spd": 110,
            "spe": 65,
            "weight": 25,
            "height": 0.9,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 136,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Porygon",
            "hp": 65,
            "atk": 60,
            "def": 70,
            "spa": 75,
            "spd": 75,
            "spe": 40,
            "weight": 36.5,
            "height": 0.8,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 137,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Omanyte",
            "hp": 35,
            "atk": 40,
            "def": 100,
            "spa": 90,
            "spd": 90,
            "spe": 35,
            "weight": 7.5,
            "height": 0.4,
            "types": ["Rock", "Water"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 138,
                "evos": ["Omastar"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Omastar",
            "hp": 70,
            "atk": 60,
            "def": 125,
            "spa": 115,
            "spd": 115,
            "spe": 55,
            "weight": 35,
            "height": 1,
            "types": ["Rock", "Water"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 139,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kakuna",
            "hp": 45,
            "atk": 25,
            "def": 50,
            "spa": 25,
            "spd": 25,
            "spe": 35,
            "weight": 10,
            "height": 0.6,
            "types": ["Bug", "Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 14,
                "evos": ["Beedrill"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kabuto",
            "hp": 30,
            "atk": 80,
            "def": 90,
            "spa": 45,
            "spd": 45,
            "spe": 55,
            "weight": 11.5,
            "height": 0.5,
            "types": ["Rock", "Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 140,
                "evos": ["Kabutops"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kabutops",
            "hp": 60,
            "atk": 115,
            "def": 105,
            "spa": 70,
            "spd": 70,
            "spe": 80,
            "weight": 40.5,
            "height": 1.3,
            "types": ["Rock", "Water"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 141,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Aerodactyl",
            "hp": 80,
            "atk": 105,
            "def": 65,
            "spa": 60,
            "spd": 60,
            "spe": 130,
            "weight": 59,
            "height": 1.8,
            "types": ["Rock", "Flying"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 142,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Snorlax",
            "hp": 160,
            "atk": 110,
            "def": 65,
            "spa": 65,
            "spd": 65,
            "spe": 30,
            "weight": 460,
            "height": 2.1,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 143,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Articuno",
            "hp": 90,
            "atk": 85,
            "def": 100,
            "spa": 125,
            "spd": 125,
            "spe": 85,
            "weight": 55.4,
            "height": 1.7,
            "types": ["Ice", "Flying"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 144,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Zapdos",
            "hp": 90,
            "atk": 90,
            "def": 85,
            "spa": 125,
            "spd": 125,
            "spe": 100,
            "weight": 52.6,
            "height": 1.6,
            "types": ["Electric", "Flying"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 145,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Moltres",
            "hp": 90,
            "atk": 100,
            "def": 90,
            "spa": 125,
            "spd": 125,
            "spe": 90,
            "weight": 60,
            "height": 2,
            "types": ["Fire", "Flying"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 146,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dratini",
            "hp": 41,
            "atk": 64,
            "def": 45,
            "spa": 50,
            "spd": 50,
            "spe": 50,
            "weight": 3.3,
            "height": 1.8,
            "types": ["Dragon"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 147,
                "evos": ["Dragonair"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dragonair",
            "hp": 61,
            "atk": 84,
            "def": 65,
            "spa": 70,
            "spd": 70,
            "spe": 70,
            "weight": 16.5,
            "height": 4,
            "types": ["Dragon"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 148,
                "evos": ["Dragonite"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dragonite",
            "hp": 91,
            "atk": 134,
            "def": 95,
            "spa": 100,
            "spd": 100,
            "spe": 80,
            "weight": 210,
            "height": 2.2,
            "types": ["Dragon", "Flying"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 149,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Beedrill",
            "hp": 65,
            "atk": 80,
            "def": 40,
            "spa": 45,
            "spd": 45,
            "spe": 75,
            "weight": 29.5,
            "height": 1,
            "types": ["Bug", "Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 15,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Mewtwo",
            "hp": 106,
            "atk": 110,
            "def": 90,
            "spa": 154,
            "spd": 154,
            "spe": 130,
            "weight": 122,
            "height": 2,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["Uber"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 150,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Mew",
            "hp": 100,
            "atk": 100,
            "def": 100,
            "spa": 100,
            "spd": 100,
            "spe": 100,
            "weight": 4,
            "height": 0.4,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["Uber"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 151,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Pidgey",
            "hp": 40,
            "atk": 45,
            "def": 40,
            "spa": 35,
            "spd": 35,
            "spe": 56,
            "weight": 1.8,
            "height": 0.3,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 16,
                "evos": ["Pidgeotto"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Pidgeotto",
            "hp": 63,
            "atk": 60,
            "def": 55,
            "spa": 50,
            "spd": 50,
            "spe": 71,
            "weight": 30,
            "height": 1.1,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 17,
                "evos": ["Pidgeot"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Pidgeot",
            "hp": 83,
            "atk": 80,
            "def": 75,
            "spa": 70,
            "spd": 70,
            "spe": 91,
            "weight": 39.5,
            "height": 1.5,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 18,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Rattata",
            "hp": 30,
            "atk": 56,
            "def": 35,
            "spa": 25,
            "spd": 25,
            "spe": 72,
            "weight": 3.5,
            "height": 0.3,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 19,
                "evos": ["Raticate"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Ivysaur",
            "hp": 60,
            "atk": 62,
            "def": 63,
            "spa": 80,
            "spd": 80,
            "spe": 60,
            "weight": 13,
            "height": 1,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 2,
                "evos": ["Venusaur"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Raticate",
            "hp": 55,
            "atk": 81,
            "def": 60,
            "spa": 50,
            "spd": 50,
            "spe": 97,
            "weight": 18.5,
            "height": 0.7,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 20,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Spearow",
            "hp": 40,
            "atk": 60,
            "def": 30,
            "spa": 31,
            "spd": 31,
            "spe": 70,
            "weight": 2,
            "height": 0.3,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 21,
                "evos": ["Fearow"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Fearow",
            "hp": 65,
            "atk": 90,
            "def": 65,
            "spa": 61,
            "spd": 61,
            "spe": 100,
            "weight": 38,
            "height": 1.2,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 22,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Ekans",
            "hp": 35,
            "atk": 60,
            "def": 44,
            "spa": 40,
            "spd": 40,
            "spe": 55,
            "weight": 6.9,
            "height": 2,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 23,
                "evos": ["Arbok"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Arbok",
            "hp": 60,
            "atk": 85,
            "def": 69,
            "spa": 65,
            "spd": 65,
            "spe": 80,
            "weight": 65,
            "height": 3.5,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 24,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Pikachu",
            "hp": 35,
            "atk": 55,
            "def": 30,
            "spa": 50,
            "spd": 50,
            "spe": 90,
            "weight": 6,
            "height": 0.4,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 25,
                "evos": ["Raichu"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Raichu",
            "hp": 60,
            "atk": 90,
            "def": 55,
            "spa": 90,
            "spd": 90,
            "spe": 100,
            "weight": 30,
            "height": 0.8,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["NUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 26,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Sandshrew",
            "hp": 50,
            "atk": 75,
            "def": 85,
            "spa": 30,
            "spd": 30,
            "spe": 40,
            "weight": 12,
            "height": 0.6,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 27,
                "evos": ["Sandslash"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Sandslash",
            "hp": 75,
            "atk": 100,
            "def": 110,
            "spa": 55,
            "spd": 55,
            "spe": 65,
            "weight": 29.5,
            "height": 1,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 28,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidoran-F",
            "hp": 55,
            "atk": 47,
            "def": 52,
            "spa": 40,
            "spd": 40,
            "spe": 41,
            "weight": 7,
            "height": 0.4,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 29,
                "evos": ["Nidorina"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Venusaur",
            "hp": 80,
            "atk": 82,
            "def": 83,
            "spa": 100,
            "spd": 100,
            "spe": 80,
            "weight": 100,
            "height": 2,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 3,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidorina",
            "hp": 70,
            "atk": 62,
            "def": 67,
            "spa": 55,
            "spd": 55,
            "spe": 56,
            "weight": 20,
            "height": 0.8,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 30,
                "evos": ["Nidoqueen"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidoqueen",
            "hp": 90,
            "atk": 82,
            "def": 87,
            "spa": 75,
            "spd": 75,
            "spe": 76,
            "weight": 60,
            "height": 1.3,
            "types": ["Poison", "Ground"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 31,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidoran-M",
            "hp": 46,
            "atk": 57,
            "def": 40,
            "spa": 40,
            "spd": 40,
            "spe": 50,
            "weight": 9,
            "height": 0.5,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 32,
                "evos": ["Nidorino"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidorino",
            "hp": 61,
            "atk": 72,
            "def": 57,
            "spa": 55,
            "spd": 55,
            "spe": 65,
            "weight": 19.5,
            "height": 0.9,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 33,
                "evos": ["Nidoking"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Nidoking",
            "hp": 81,
            "atk": 92,
            "def": 77,
            "spa": 75,
            "spd": 75,
            "spe": 85,
            "weight": 62,
            "height": 1.4,
            "types": ["Poison", "Ground"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 34,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Clefairy",
            "hp": 70,
            "atk": 45,
            "def": 48,
            "spa": 60,
            "spd": 60,
            "spe": 35,
            "weight": 7.5,
            "height": 0.6,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 35,
                "evos": ["Clefable"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Clefable",
            "hp": 95,
            "atk": 70,
            "def": 73,
            "spa": 85,
            "spd": 85,
            "spe": 60,
            "weight": 40,
            "height": 1.3,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 36,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Vulpix",
            "hp": 38,
            "atk": 41,
            "def": 40,
            "spa": 65,
            "spd": 65,
            "spe": 65,
            "weight": 9.9,
            "height": 0.6,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 37,
                "evos": ["Ninetales"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Ninetales",
            "hp": 73,
            "atk": 76,
            "def": 75,
            "spa": 100,
            "spd": 100,
            "spe": 100,
            "weight": 19.9,
            "height": 1.1,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 38,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Jigglypuff",
            "hp": 115,
            "atk": 45,
            "def": 20,
            "spa": 25,
            "spd": 25,
            "spe": 20,
            "weight": 5.5,
            "height": 0.5,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 39,
                "evos": ["Wigglytuff"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Charmander",
            "hp": 39,
            "atk": 52,
            "def": 43,
            "spa": 50,
            "spd": 50,
            "spe": 65,
            "weight": 8.5,
            "height": 0.6,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 4,
                "evos": ["Charmeleon"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Wigglytuff",
            "hp": 140,
            "atk": 70,
            "def": 45,
            "spa": 50,
            "spd": 50,
            "spe": 45,
            "weight": 12,
            "height": 1,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 40,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Zubat",
            "hp": 40,
            "atk": 45,
            "def": 35,
            "spa": 40,
            "spd": 40,
            "spe": 55,
            "weight": 7.5,
            "height": 0.8,
            "types": ["Poison", "Flying"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 41,
                "evos": ["Golbat"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Golbat",
            "hp": 75,
            "atk": 80,
            "def": 70,
            "spa": 75,
            "spd": 75,
            "spe": 90,
            "weight": 55,
            "height": 1.6,
            "types": ["Poison", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 42,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Oddish",
            "hp": 45,
            "atk": 50,
            "def": 55,
            "spa": 75,
            "spd": 75,
            "spe": 30,
            "weight": 5.4,
            "height": 0.5,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 43,
                "evos": ["Gloom"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Gloom",
            "hp": 60,
            "atk": 65,
            "def": 70,
            "spa": 85,
            "spd": 85,
            "spe": 40,
            "weight": 8.6,
            "height": 0.8,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 44,
                "evos": ["Vileplume"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Vileplume",
            "hp": 75,
            "atk": 80,
            "def": 85,
            "spa": 100,
            "spd": 100,
            "spe": 50,
            "weight": 18.6,
            "height": 1.2,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 45,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Paras",
            "hp": 35,
            "atk": 70,
            "def": 55,
            "spa": 55,
            "spd": 55,
            "spe": 25,
            "weight": 5.4,
            "height": 0.3,
            "types": ["Bug", "Grass"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 46,
                "evos": ["Parasect"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Parasect",
            "hp": 60,
            "atk": 95,
            "def": 80,
            "spa": 80,
            "spd": 80,
            "spe": 30,
            "weight": 29.5,
            "height": 1,
            "types": ["Bug", "Grass"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 47,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Venonat",
            "hp": 60,
            "atk": 55,
            "def": 50,
            "spa": 40,
            "spd": 40,
            "spe": 45,
            "weight": 30,
            "height": 1,
            "types": ["Bug", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 48,
                "evos": ["Venomoth"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Venomoth",
            "hp": 70,
            "atk": 65,
            "def": 60,
            "spa": 90,
            "spd": 90,
            "spe": 90,
            "weight": 12.5,
            "height": 1.5,
            "types": ["Bug", "Poison"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 49,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Charmeleon",
            "hp": 58,
            "atk": 64,
            "def": 58,
            "spa": 65,
            "spd": 65,
            "spe": 80,
            "weight": 19,
            "height": 1.1,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 5,
                "evos": ["Charizard"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Diglett",
            "hp": 10,
            "atk": 55,
            "def": 25,
            "spa": 45,
            "spd": 45,
            "spe": 95,
            "weight": 0.8,
            "height": 0.2,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 50,
                "evos": ["Dugtrio"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dugtrio",
            "hp": 35,
            "atk": 80,
            "def": 50,
            "spa": 70,
            "spd": 70,
            "spe": 120,
            "weight": 33.3,
            "height": 0.7,
            "types": ["Ground"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 51,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Meowth",
            "hp": 40,
            "atk": 45,
            "def": 35,
            "spa": 40,
            "spd": 40,
            "spe": 90,
            "weight": 4.2,
            "height": 0.4,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 52,
                "evos": ["Persian"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Persian",
            "hp": 65,
            "atk": 70,
            "def": 60,
            "spa": 65,
            "spd": 65,
            "spe": 115,
            "weight": 32,
            "height": 1,
            "types": ["Normal"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 53,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Psyduck",
            "hp": 50,
            "atk": 52,
            "def": 48,
            "spa": 50,
            "spd": 50,
            "spe": 55,
            "weight": 19.6,
            "height": 0.8,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 54,
                "evos": ["Golduck"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Golduck",
            "hp": 80,
            "atk": 82,
            "def": 78,
            "spa": 80,
            "spd": 80,
            "spe": 85,
            "weight": 76.6,
            "height": 1.7,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 55,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Mankey",
            "hp": 40,
            "atk": 80,
            "def": 35,
            "spa": 35,
            "spd": 35,
            "spe": 70,
            "weight": 28,
            "height": 0.5,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 56,
                "evos": ["Primeape"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Primeape",
            "hp": 65,
            "atk": 105,
            "def": 60,
            "spa": 60,
            "spd": 60,
            "spe": 95,
            "weight": 32,
            "height": 1,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 57,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Growlithe",
            "hp": 55,
            "atk": 70,
            "def": 45,
            "spa": 50,
            "spd": 50,
            "spe": 60,
            "weight": 19,
            "height": 0.7,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 58,
                "evos": ["Arcanine"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Arcanine",
            "hp": 90,
            "atk": 110,
            "def": 80,
            "spa": 80,
            "spd": 80,
            "spe": 95,
            "weight": 155,
            "height": 1.9,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 59,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Charizard",
            "hp": 78,
            "atk": 84,
            "def": 78,
            "spa": 85,
            "spd": 85,
            "spe": 100,
            "weight": 90.5,
            "height": 1.7,
            "types": ["Fire", "Flying"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 6,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Poliwag",
            "hp": 40,
            "atk": 50,
            "def": 40,
            "spa": 40,
            "spd": 40,
            "spe": 90,
            "weight": 12.4,
            "height": 0.6,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 60,
                "evos": ["Poliwhirl"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Poliwhirl",
            "hp": 65,
            "atk": 65,
            "def": 65,
            "spa": 50,
            "spd": 50,
            "spe": 90,
            "weight": 20,
            "height": 1,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 61,
                "evos": ["Poliwrath"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Poliwrath",
            "hp": 90,
            "atk": 85,
            "def": 95,
            "spa": 70,
            "spd": 70,
            "spe": 70,
            "weight": 54,
            "height": 1.3,
            "types": ["Water", "Fighting"],
            "abilities": [],
            "formats": ["NUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 62,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Abra",
            "hp": 25,
            "atk": 20,
            "def": 15,
            "spa": 105,
            "spd": 105,
            "spe": 90,
            "weight": 19.5,
            "height": 0.9,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 63,
                "evos": ["Kadabra"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kadabra",
            "hp": 40,
            "atk": 35,
            "def": 30,
            "spa": 120,
            "spd": 120,
            "spe": 105,
            "weight": 56.5,
            "height": 1.3,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 64,
                "evos": ["Alakazam"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Alakazam",
            "hp": 55,
            "atk": 50,
            "def": 45,
            "spa": 135,
            "spd": 135,
            "spe": 120,
            "weight": 48,
            "height": 1.5,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 65,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Machop",
            "hp": 70,
            "atk": 80,
            "def": 50,
            "spa": 35,
            "spd": 35,
            "spe": 35,
            "weight": 19.5,
            "height": 0.8,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 66,
                "evos": ["Machoke"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Machoke",
            "hp": 80,
            "atk": 100,
            "def": 70,
            "spa": 50,
            "spd": 50,
            "spe": 45,
            "weight": 70.5,
            "height": 1.5,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 67,
                "evos": ["Machamp"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Machamp",
            "hp": 90,
            "atk": 130,
            "def": 80,
            "spa": 65,
            "spd": 65,
            "spe": 55,
            "weight": 130,
            "height": 1.6,
            "types": ["Fighting"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 68,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Bellsprout",
            "hp": 50,
            "atk": 75,
            "def": 35,
            "spa": 70,
            "spd": 70,
            "spe": 40,
            "weight": 4,
            "height": 0.7,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 69,
                "evos": ["Weepinbell"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Squirtle",
            "hp": 44,
            "atk": 48,
            "def": 65,
            "spa": 50,
            "spd": 50,
            "spe": 43,
            "weight": 9,
            "height": 0.5,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 7,
                "evos": ["Wartortle"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Weepinbell",
            "hp": 65,
            "atk": 90,
            "def": 50,
            "spa": 85,
            "spd": 85,
            "spe": 55,
            "weight": 6.4,
            "height": 1,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 70,
                "evos": ["Victreebel"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Victreebel",
            "hp": 80,
            "atk": 105,
            "def": 65,
            "spa": 100,
            "spd": 100,
            "spe": 70,
            "weight": 15.5,
            "height": 1.7,
            "types": ["Grass", "Poison"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 71,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Tentacool",
            "hp": 40,
            "atk": 40,
            "def": 35,
            "spa": 100,
            "spd": 100,
            "spe": 70,
            "weight": 45.5,
            "height": 0.9,
            "types": ["Water", "Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 72,
                "evos": ["Tentacruel"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Tentacruel",
            "hp": 80,
            "atk": 70,
            "def": 65,
            "spa": 120,
            "spd": 120,
            "spe": 100,
            "weight": 55,
            "height": 1.6,
            "types": ["Water", "Poison"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 73,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Geodude",
            "hp": 40,
            "atk": 80,
            "def": 100,
            "spa": 30,
            "spd": 30,
            "spe": 20,
            "weight": 20,
            "height": 0.4,
            "types": ["Rock", "Ground"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 74,
                "evos": ["Graveler"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Graveler",
            "hp": 55,
            "atk": 95,
            "def": 115,
            "spa": 45,
            "spd": 45,
            "spe": 35,
            "weight": 105,
            "height": 1,
            "types": ["Rock", "Ground"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 75,
                "evos": ["Golem"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Golem",
            "hp": 80,
            "atk": 110,
            "def": 130,
            "spa": 55,
            "spd": 55,
            "spe": 45,
            "weight": 300,
            "height": 1.4,
            "types": ["Rock", "Ground"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 76,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Ponyta",
            "hp": 50,
            "atk": 85,
            "def": 55,
            "spa": 65,
            "spd": 65,
            "spe": 90,
            "weight": 30,
            "height": 1,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 77,
                "evos": ["Rapidash"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Rapidash",
            "hp": 65,
            "atk": 100,
            "def": 70,
            "spa": 80,
            "spd": 80,
            "spe": 105,
            "weight": 95,
            "height": 1.7,
            "types": ["Fire"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 78,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Slowpoke",
            "hp": 90,
            "atk": 65,
            "def": 65,
            "spa": 40,
            "spd": 40,
            "spe": 15,
            "weight": 36,
            "height": 1.2,
            "types": ["Water", "Psychic"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 79,
                "evos": ["Slowbro"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Wartortle",
            "hp": 59,
            "atk": 63,
            "def": 80,
            "spa": 65,
            "spd": 65,
            "spe": 58,
            "weight": 22.5,
            "height": 1,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NFE"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 8,
                "evos": ["Blastoise"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Slowbro",
            "hp": 95,
            "atk": 75,
            "def": 110,
            "spa": 80,
            "spd": 80,
            "spe": 30,
            "weight": 78.5,
            "height": 1.6,
            "types": ["Water", "Psychic"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 80,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Magnemite",
            "hp": 25,
            "atk": 35,
            "def": 70,
            "spa": 95,
            "spd": 95,
            "spe": 45,
            "weight": 6,
            "height": 0.3,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 81,
                "evos": ["Magneton"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Magneton",
            "hp": 50,
            "atk": 60,
            "def": 95,
            "spa": 120,
            "spd": 120,
            "spe": 70,
            "weight": 60,
            "height": 1,
            "types": ["Electric"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 82,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Farfetch'd",
            "hp": 52,
            "atk": 65,
            "def": 55,
            "spa": 58,
            "spd": 58,
            "spe": 60,
            "weight": 15,
            "height": 0.8,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 83,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Doduo",
            "hp": 35,
            "atk": 85,
            "def": 45,
            "spa": 35,
            "spd": 35,
            "spe": 75,
            "weight": 39.2,
            "height": 1.4,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 84,
                "evos": ["Dodrio"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dodrio",
            "hp": 60,
            "atk": 110,
            "def": 70,
            "spa": 60,
            "spd": 60,
            "spe": 100,
            "weight": 85.2,
            "height": 1.8,
            "types": ["Normal", "Flying"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 85,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Seel",
            "hp": 65,
            "atk": 45,
            "def": 55,
            "spa": 70,
            "spd": 70,
            "spe": 45,
            "weight": 90,
            "height": 1.1,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 86,
                "evos": ["Dewgong"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Dewgong",
            "hp": 90,
            "atk": 70,
            "def": 80,
            "spa": 95,
            "spd": 95,
            "spe": 70,
            "weight": 120,
            "height": 1.7,
            "types": ["Water", "Ice"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 87,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Grimer",
            "hp": 80,
            "atk": 80,
            "def": 50,
            "spa": 40,
            "spd": 40,
            "spe": 25,
            "weight": 30,
            "height": 0.9,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 88,
                "evos": ["Muk"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Muk",
            "hp": 105,
            "atk": 105,
            "def": 75,
            "spa": 65,
            "spd": 65,
            "spe": 50,
            "weight": 30,
            "height": 1.2,
            "types": ["Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 89,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Blastoise",
            "hp": 79,
            "atk": 83,
            "def": 100,
            "spa": 85,
            "spd": 85,
            "spe": 78,
            "weight": 85.5,
            "height": 1.6,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 9,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Shellder",
            "hp": 30,
            "atk": 65,
            "def": 100,
            "spa": 45,
            "spd": 45,
            "spe": 40,
            "weight": 4,
            "height": 0.3,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 90,
                "evos": ["Cloyster"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Cloyster",
            "hp": 50,
            "atk": 95,
            "def": 180,
            "spa": 85,
            "spd": 85,
            "spe": 70,
            "weight": 132.5,
            "height": 1.5,
            "types": ["Water", "Ice"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 91,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Gastly",
            "hp": 30,
            "atk": 35,
            "def": 30,
            "spa": 100,
            "spd": 100,
            "spe": 80,
            "weight": 0.1,
            "height": 1.3,
            "types": ["Ghost", "Poison"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 92,
                "evos": ["Haunter"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Haunter",
            "hp": 45,
            "atk": 50,
            "def": 45,
            "spa": 115,
            "spd": 115,
            "spe": 95,
            "weight": 0.1,
            "height": 1.6,
            "types": ["Ghost", "Poison"],
            "abilities": [],
            "formats": ["UU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 93,
                "evos": ["Gengar"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Gengar",
            "hp": 60,
            "atk": 65,
            "def": 60,
            "spa": 130,
            "spd": 130,
            "spe": 110,
            "weight": 40.5,
            "height": 1.5,
            "types": ["Ghost", "Poison"],
            "abilities": [],
            "formats": ["OU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 94,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Onix",
            "hp": 35,
            "atk": 45,
            "def": 160,
            "spa": 30,
            "spd": 30,
            "spe": 70,
            "weight": 210,
            "height": 8.8,
            "types": ["Rock", "Ground"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 95,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Drowzee",
            "hp": 60,
            "atk": 48,
            "def": 45,
            "spa": 90,
            "spd": 90,
            "spe": 42,
            "weight": 32.4,
            "height": 1,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["PU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 96,
                "evos": ["Hypno"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Hypno",
            "hp": 85,
            "atk": 73,
            "def": 70,
            "spa": 115,
            "spd": 115,
            "spe": 67,
            "weight": 75.6,
            "height": 1.6,
            "types": ["Psychic"],
            "abilities": [],
            "formats": ["UUBL"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 97,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Krabby",
            "hp": 30,
            "atk": 105,
            "def": 90,
            "spa": 25,
            "spd": 25,
            "spe": 50,
            "weight": 6.5,
            "height": 0.4,
            "types": ["Water"],
            "abilities": [],
            "formats": ["LC"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 98,
                "evos": ["Kingler"],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
        {
            "name": "Kingler",
            "hp": 55,
            "atk": 130,
            "def": 115,
            "spa": 50,
            "spd": 50,
            "spe": 75,
            "weight": 60,
            "height": 1.3,
            "types": ["Water"],
            "abilities": [],
            "formats": ["NU"],
            "isNonstandard": "Standard",
            "oob": {
                "dex_number": 99,
                "evos": [],
                "alts": [],
                "genfamily": ["RB", "GS", "RS", "DP", "BW", "XY", "SM", "SS", "SV"],
            },
        },
    ]

    print(f"number of pokes: {len(list_of_poke_dicts)}")

    poke_stats = {}

    for d in list_of_poke_dicts:
        poke_stats[d["name"].lower()] = {
            "tier": d["formats"],
            "type": d["types"],
            "stats": {
                "hp": d["hp"],
                "atk": d["atk"],
                "def": d["def"],
                "spa": d["spa"],
                "spd": d["spd"],
                "spe": d["spe"],
            },
        }
        # print(f'some poke_stats {poke_stats}')
        # print(poke_stats[d['name'].lower()])
        poke_stats[d["name"].lower()]["base_stat_total"] = sum(
            poke_stats[d["name"].lower()]["stats"].values()
        )

    # poke_choice = input("Which pokemon you wanna know about?")

    # print(type(poke_choice))

    # print(f"stats for {str(poke_choice)}: {poke_stats[str(poke_choice)]}")

    with open("poke_base_stats.pkl", "wb") as fp:
        pickle.dump(poke_stats, fp)

